version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: asciidoctor
    versions:
    - 2.0.12
    - 2.0.13
    - 2.0.14
