trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.6'

- script: |
    gem install bundler:2.0.1

- script: |
    bundler --binstubs
    ./bin/rake

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: 'the_road_from_java8_to_java11-$(Build.BuildNumber).pdf'
    targetPath: 'the_road_from_java8_to_java11.pdf'
