image: ruby:2.5.3

pipelines:
  default:
      - step:
          script:
            - bundle --binstubs
            - export OUTFILE="ignore"
            - ./bin/rake pdf
  tags:
    v*:
      - step:
          script:
            - bundle --binstubs
            - export OUTFILE="the_road_from_java8_to_java11-${BITBUCKET_TAG}"
            - ./bin/rake pdf
            - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"$OUTFILE"
