= The road from Java8 to Java11
Davide Angelocola <davide.angelocola@gmail.com>

:author: Davide Angelocola
:firstname: Davide
:lastname: Angelocola
:email: davide.angelocola@gmail.com
:copyright: CC-BY-SA 4.0
:doctype: book
:creator: {author}
:source-highlighter: prettify
:homepage: https://dfa.bitbucket.io

== Introduction

As Java developers we will very busy upgrading our code bases to newest Java releases.
This will be a slow process, especially regarding the upgrade from classpath to the module
path.

It is important to document, with well written examples, how to take advantage
of new Java classes and idioms.

=== Principles

* the main focus is on the language level changes
* use standard library as much as possible
* redirect to release notes, JEPS and bug reports
* examples are compiled with JShell

==== Author

- {firstname} {lastname} <{email}>

==== Contributors

- Karrie Moore
- Alessandro Sebastiani

==== License

This document is licensed under a https://creativecommons.org/licenses/by-sa/4.0/[Creative Commons Attribution-ShareAlike 4.0 International License].

== Upgrade to Java11

Java11 is the new LTS version, check http://jdk.java.net/11/release-notes for official release notes.

The big feature are:

* new java.net.http module
* TLS 1.3
* removal of Corba and Java EE
* removal of Web Start, with no clear replacement
* removal of Java applets
* removal of JavaFX: the FX libraries have moved to the OpenJFX project
* paid support for Oracle JDK

The last point is critical, since now in order to use JDK11 in production you have to subscribe
to Oracle, details here: https://www.oracle.com/technetwork/java/javaseproducts/overview/javasesubscriptionfaq-4891443.html.

=== Upgrade problems

* http://openjdk.java.net/jeps/320 provide missing JARs;
* removal of `Thread.destroy()` and `Thread.stop(Throwable)` Methods, see https://bugs.openjdk.java.net/browse/JDK-8204243
* removal of `com.sun.awt.AWTUtilities` Class, see https://bugs.openjdk.java.net/browse/JDK-8200149
* source incompatibility for `java.util.Stream.toArray(null)`, see https://bugs.openjdk.java.net/browse/JDK-8060192
* removal of removal of `sun.misc.Unsafe.defineClass`, see https://bugs.openjdk.java.net/browse/JDK-8193033

JAXB is not provided by the JDK anymore so it is required to provide an external dependency for it.
Using apache maven would be:

----
<dependency>
	<groupId>javax.xml.bind</groupId>
	<artifactId>jaxb-api</artifactId>
	<version>2.3.0</version>
</dependency>
<dependency>
	<groupId>org.glassfish.jaxb</groupId>
	<artifactId>jaxb-runtime</artifactId>
	<version>2.3.0.1</version>
</dependency>
----

This is a very good reference: https://stackoverflow.com/questions/48204141/replacements-for-deprecated-jpms-modules-with-java-ee-apis/48204154#48204154

===  java.net.http

http://openjdk.java.net/groups/net/httpclient/intro.html

Introduced in Java9, and promoted from incubator in Java11.
.TODO: examples

=== Security

This version includes several new important and modern crypto features:

* TLS 1.3, see https://bugs.openjdk.java.net/browse/JDK-8202625;
* ChaCha20 & Poly1305 crypto algorithms;
* Key Agreement with Curve25519 and Curve448.

=== var in lambda

http://openjdk.java.net/jeps/323

----
(var x, var y) -> x.process(y)
----

now it is equivalent to:

----
(x, y) -> x.process(y)
----

The primary advantage is that now it is possible to annotate parameters, e.g. for static analysis.

=== `Optional.isEmpty()`

In addition of `Optional.isPresent` now it is possible to use `Optional.isEmpty`:

----
Optional<String> arg = ...;
if (arg.isEmpty()) {
	logger.warn("arg is empty, defaulting to 'foo'");
}
----

=== `ArrayIndexOutOfBounds`

Improved error message with index and current size of the array:

----
jshell> int[] a = {1}
a ==> int[1] { 1 }

jshell> a[4]
|  Exception java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 1
|        at (#2:1)
----

In previous Java versions we have a much more cryptic message:

----
jshell> int[] a ={1}
a ==> int[1] { 1 }

jshell> a[4]
|  java.lang.ArrayIndexOutOfBoundsException thrown: 4
|        at (#4:1)
----

=== `Character.toString(int)`

This method returns the string representation for the given Unicode code point as shown below:

[source,java]
----
include::snippets/character_toString.jsh[]
----

=== `String.lines()`

Sometimes this is very convenient: get a stream divided by line breaks:

[source,java]
----
jshell> "a\nb\nc\n".lines().toUpperCase().toArray()
$1 ==> Object[2] { "A", "B", "C }
----

=== `String.lines()`

Repeat String for the specified number of times:

[source,java]
----
jshell> "test".repeat(3)
$7 ==> "testtesttest"
----

[NOTE] check bondaries (-1, MAX_VALUE)


=== `String.isBlank()`

This is correct but too technical, and perhaps the intent is not clear:

----
boolean blank = string.codePoints().allMatch(Character::isWhitespace);
----

https://bugs.openjdk.java.net/browse/JDK-8200437

[source,java]
----
jshell> var halfSpace = "\u0020"
halfSpace ==> " "

jshell> halfSpace.trim()
$2 ==> ""

jshell> var fullSpace = "\u3000"
fullSpace ==> "　"

jshell> fullSpace.trim()
$4 ==> "　"
----

=== `String.strip()`

https://bugs.openjdk.java.net/browse/JDK-8200378

While almost the same as `trim()`/`trimLeft()`/`trimRight(), this takes full-width spaces as a
space (0x20 ascii character). This new method is Unicode-aware, by using `Character.isWhitespace()`.
[source,java]
----
jshell> var halfSpace = "\u0020"
halfSpace ==> " "

jshell> halfSpace.trim()
$2 ==> ""

jshell> var fullSpace = "\u3000"
jshell> fullSpace.trim()
$4 ==> ""
----

TODO: cover also stripLeading()/stripTrailing()

=== Null objects for Reader/Writer and InputStream/OutputStream

https://download.java.net/java/early_access/jdk11/docs/api/java.base/java/io/Reader.html#nullReader()

* `Reader.nullReader()`
* `Writer.nullWriter()`
* `InputStream.nullInputStream()`
* `OutputStream.nullOutputStream()`

These objects are very useful during unit testing.

=== `java.nio.file.Files`

* `String readString(Path, Charset`): reads all content from a file into a string, decoding from bytes to characters using the specified charset;
* `Path writeString(Path, CharSequence, Charset, OpenOption[])`: write a `CharSequence` (e.g. `String`, `StringBuilder`) to a file. Characters are encoded into bytes using the specified charset.

it is very convenient to use `java.nio.charset.StandardCharsets`, https://docs.oracle.com/javase/7/docs/api/java/nio/charset/StandardCharsets.html

=== `java.nio.Path`

This is a very nice shorcut to build paths:

----
jshell> Path.of("dir", "subdir", "file")
$2 ==> dir/subdir/file
----

Returns a `Path` by converting a path string, or a sequence of strings that when joined form
a path string. Please note that this API is following the _Item 42_ of _Effective Java_:

----
jshell> Path.of()
|  Error:
|  no suitable method found for of(no arguments)
|      method java.nio.file.Path.of(java.lang.String,java.lang.String...) is not applicable
|        (actual and formal argument lists differ in length)
|      method java.nio.file.Path.of(java.net.URI) is not applicable
|        (actual and formal argument lists differ in length)
|  Path.of()
|  ^-----^
----

because the definition is:

----
static Path	of(String first, String... more)
----
=== Launch Single-File Source-Code Programs

http://openjdk.java.net/jeps/330

----
dfa@aman:~ $ vim aa.java
dfa@aman:~ $ cat aa.java
public class Test {
	public static void main(String[] args) {
		System.out.println("hello world!");
	}
}
dfa@aman:~ $ java aa.java
hello world!
----

=== Unicode

http://openjdk.java.net/jeps/327

This release includes combined support for both _Unicode 9.0_ as well as _Unicode 10.0_.

By now it is possible to use Bitcoin, since the Bitcoin sign is part of _Unicode 10.0_
(released June 2017) with code point `U+20BF`.

== Upgrade to Java10

This is the big new feature of Java 10, introduced by http://openjdk.java.net/jeps/286
There are also other important features:

 * JEP 304 garbage collector interface
 * JEP 317 experimental java based JIT compiler
 * JEP 307 Parallel full gc for G1
 * JEP 310 application class-data sharing
 * JEP 312 thread-local handshakes
 * JEP 313 javah removal
 * JEP 314 unicode extentions
 * JEP 319 root certificates, to easy migration from oracle JDK -> open JDK
 * removal of `policytool`

=== local type inference

[source,java]
----
include::snippets/java10_var.jsh[]
----

It is important to know that var is not a keyword, it is a special type. In this way you can continue to use var as variable name or method name.

Now it is possible to express things not possible before, use wisely:

[source,java]
----
var a = new Object() {

   void m() {

   }

};

a.m();

----

=== Docker awareness

JVM now can detect cpu/memory settings when run inside a container.

TODO: example

=== new javadoc `@summary` tag

https://bugs.openjdk.java.net/browse/JDK-8173425

In order to be precise and avoid ambiguities around the special handling of the first sentence of javadoc,
it is possible to use `@summary`:

----
{@summary This is the first sentence.} This is the second sentence.
----


=== `java.io.Reader.transferTo(Writer)`

This is a long awaited feature, usually provided by external libraries such as Apache IOUtils.

[source, java]
----
jshell> import java.io.*

jshell> var a = new StringReader("hello world");
a ==> java.io.StringReader@3abbfa04

jshell> var b = new StringWriter();
b ==>

jshell> a.transferTo(b)
$4 ==> 11

jshell> b
b ==> hello world
----

=== `RuntimeMXBean.getPid()`

This new method returns the process ID representing the running Java virtual machine:

----
jshell> import java.lang.management.*;

jshell> ManagementFactory.getRuntimeMXBean().getPid()
$8 ==> 11429

----

== Upgrade to Java9

Java9 delivers an impressive list of features (http://openjdk.java.net/projects/jdk9/).

Two of the most important are:
- Project Jigsaw http://openjdk.java.net/projects/jigsaw/
- Jshell http://openjdk.java.net/jeps/222
- new HTTP client http://openjdk.java.net/jeps/110

Describing any of these items is beyond the scope of this document, especially Project Jigsaw (modules). By the way: __you don’t need modules to run on Java 9__.

=== Immutable collections

JEP 269 http://openjdk.java.net/jeps/269 introduced some new factory methods for collections.
New APIs are:

[source,java]
----
Set<Integer> set = Set.of(1,2,3,4);
List<Integer> list = List.of(1,2,1,2);
Map<String, Integer> map = Map.of("key1", 1, "key2", 2);
Map<String, Integer> mapLonger = Map.ofEntries(Map.entry("key1", 1), Map.entry("key2", 2));
----

.Immutability vs views
NOTE: `Collections.unmodificable` are just read-only wrappers around original data structure: if the original datastructure is mutable, you can still see changes in the wrapper.

----
jshell> var list = new ArrayList<>()
list ==> []

jshell> var unmodificableList = Collections.unmodifiableList(list)
unmodificableList ==> []

jshell> list.add(1)
$3 ==> true

jshell> unmodificableList
unmodificableList ==> [1]
----

By using these new methods you get immutable data structures:

----
jshell> var immutableList = List.of();
immutableList ==> []

jshell> immutableList.add(1)
|  Exception java.lang.UnsupportedOperationException
|        at ImmutableCollections.uoe (ImmutableCollections.java:71)
|        at ImmutableCollections$AbstractImmutableCollection.add (ImmutableCollections.java:75)
|        at (#6:1)
----

.Gotcha:
NOTE: sometimes `List.copyOf` is a no-op

----
jshell> List<?> a = List.of(1,2,3)
a ==> [1, 2, 3]

jshell> List<?> b = List.copyOf(a)
b ==> [1, 2, 3]

jshell> a == b
$7 ==> true
----

.Gotcha:
NOTE: cannot use `Set.of` to filter aways duplicated.

[source,java]
----
jshell> Set.of(1,1)
|  java.lang.IllegalArgumentException thrown: duplicate element: 1
|        at ImmutableCollections$SetN.<init> (ImmutableCollections.java:463)
|        at Set.of (Set.java:521)
----

Now it is also possible to use `java.util.stream.Collectors`
to build an unmodificableList/Set/Map.

=== `java.util.Optional.stream()`

Given:

[source,java]
----
List<Optional<String>> listOfOptionals = something();
----

in Java8:

[source,java]
----
List<String> filteredList = listOfOptionals.stream()
  .filter(Optional::isPresent) <1>
  .map(Optional::get) <2>
  .collect(Collectors.toList());
----
<1> discarding empty optionals
<2> unwrapping optionals

in Java9 it is possible to write:

[source,java]
----
List<String> filteredList = listOfOptionals.stream()
  .flatMap(Optional::stream) <1>
  .collect(Collectors.toList());
----
<1> `Optional` as `Stream`

`Optional.stream()` is straightforward:

[source,java]
----
    public Stream<T> stream() {
        if (!isPresent()) {
            return Stream.empty();
        } else {
            return Stream.of(value);
        }
    }
----

=== `Stream.takeWhile()`/`Stream.dropWhile()`

https://bugs.openjdk.java.net/browse/JDK-8071597

Another nice addiction to the Stream API:

----
IntStream
  .iterate(1, n -> n + 1)
  .takeWhile(n -> n < 10)
  .forEach(System.out::println);
----

=== Stack walk API

http://openjdk.java.net/jeps/259

This is useful in several occasions and now it is possible to capture a partial stacktrace
in a very simple and effective way.

For example getting the caller it is trivial now:

----
StackWalker
	.getInstance(StackWalker.Option.RETAIN_CLASS_REFERENCE)
	.getCallerClass()
----

StackWalker instances are thread-safe and thus can be shared between threads: each thread will see its own stack.
Additionally a security check is performed on creation of the StackWalker instance, no further checks are performed later.

=== `@SafeVarags` on private methods

Part of JEP 213 http://openjdk.java.net/jeps/213.

https://bugs.openjdk.java.net/browse/JDK-7196160

Now it is possible to use @SafeVarargs also for private methods.

.TODO: example

=== `private` methods in interfaces

Part of JEP 213 http://openjdk.java.net/jeps/213.

.TODO: example

=== `_` identifier

Part of JEP 213 http://openjdk.java.net/jeps/213.

Now it is forbidden to use `_` as identifier.

----
jshell> Predicate<Integer> pred = _ -> false;
|  Error:
|  '_' used as an identifier
|    (use of '_' as an identifier is forbidden for lambda parameters)
|  Predicate<Integer> pred = _ -> false;
|                            ^
----

This is a trivial source-level incompatibility to fix.


=== Version

http://openjdk.java.net/jeps/223

In legacy codebases it is possible to find various ways to determine which java
version is running:

[source,java]
----
String version = Runtime.class.getPackage().getImplementationVersion();
----

[source,java]
----
double version = Double.parseDouble(System.getProperty("java.specification.version"));
----

[source,java]
----
String[] javaVersionElements = System.getProperty("java.runtime.version").split("\\.|_|-b");
----

Now we have a nice standard API to do that:

[source,java]
----
Runtime.Version version = Runtime.version();
----

`Version` it's a value object and it is `Comparable<Version>`. It is even possible to create a `Version`
instance using an externally provided version string:

[source,java]
----
include::snippets/java9_version.jsh[]
----

=== `java.lang.ProcessHandle`

Obtain information about JVM itself:

[source,java]
----
include::snippets/java9_process_info.jsh[]
----

List all system processes:
[source,java]
----
include::snippets/java9_process_list.jsh[]
----

=== `@Deprecated` enhancements

http://openjdk.java.net/jeps/277

It is possible to mark a method/class for removal (`forRemoval`) and when the deprecation started (`since`):

----
@Deprecate(forRemoval=true)
public void foo() {

}
----

----
@Deprecate(since="1.0")
public void bar() {

}
----

=== Unified JVM logging

http://openjdk.java.net/jeps/158

This is invaluable in debugging problems in production or during a big acceptance test.
Now it is possible to capture and log interesting events happening inside the JVM.
For example it is possible to include every tag around gc:

----
$ java -Xlog:gc* -jar myapp.jar
[0.012s][info][gc,heap] Heap region size: 1M
[0.018s][info][gc     ] Using G1
[0.019s][info][gc,heap,coops] Heap address: 0x00000006c0000000, size: 4096 MB, Compressed Oops mode: Zero based, Oop shift amount: 3
... application output
... exit
[1.803s][info][gc,heap,exit ] Heap
[1.803s][info][gc,heap,exit ]  garbage-first heap   total 262144K, used 11264K [0x00000006c0000000, 0x00000007c0000000)
[1.803s][info][gc,heap,exit ]   region size 1024K, 12 young (12288K), 0 survivors (0K)
[1.803s][info][gc,heap,exit ]  Metaspace       used 10805K, capacity 11186K, committed 11520K, reserved 1058816K
[1.803s][info][gc,heap,exit ]   class space    used 1042K, capacity 1203K, committed 1280K, reserved 1048576K
----

Or restrict to a more specific tag, such as gc+heap:

----
$ java -Xlog:gc,gc+heap -jar myapp.jar
[0.013s][info][gc,heap] Heap region size: 1M
[0.019s][info][gc     ] Using G1
... application output
[89.471s][info][gc,heap] GC(0) Eden regions: 24->0(151)
[89.471s][info][gc,heap] GC(0) Survivor regions: 0->2(3)
[89.471s][info][gc,heap] GC(0) Old regions: 0->0
[89.471s][info][gc,heap] GC(0) Humongous regions: 0->0
[89.471s][info][gc     ] GC(0) Pause Young (G1 Evacuation Pause) 24M->1M(256M) 3.926ms
... exit
----

=== Compact Strings

http://openjdk.java.net/jeps/254

This is just a more efficient internal representation of java.lang.String, no public methods
will be changed.

In practice, the internal representation of string has been changed from `char[]` to `byte[]` + flag.
The purpose of the flag is to store which encoding to use:
`ISO-8859-1/Latin-1` (one byte per character) or `UTF-16` (two bytes per character).

== Upgrade to Java8

The big deliver for Java8 is:

- Project Lambda http://openjdk.java.net/projects/lambda/
- ThreeTen http://openjdk.java.net/projects/threeten/

Neverthless the are hidden gem in this release that simplifies a lot certain tasks.

=== `java.io.UncheckedIOException`

This is a little know class that wraps an `IOException` with an unchecked exception.


