= What's new with Java
v0.1, 2018-09-19
:author: Davide Angelocola
:firstname: Davide
:lastname: Angelocola
:email: davide.angelocola@gmail.com
:copyright: CC-BY-SA 3.0
:doctype: book
:creator: {author}
:source-highlighter: prettify

== About the Author

You can contact {author} at {email}. {firstname} loves to hear from other developers.

== Introduction

As Java developer we spend we will busy upgrading our code bases to newest Java version.
The idea behind this article is to document in a systematic way the new Java API and features.
The section are organized in baby steps.

== Principles

* use standard library
* step by step migrations
* examples are compiled with JShell

== Upgrade to Java11

=== Character.toString(int)

This method returns the string representation for the given Unicode code point as shown below:

[source,java]
----
include::snippets/character_toString.jsh[]
----

== Upgrade to Java10

=== local type inference

This is the big new feature of Java 10, introduced by  http://openjdk.java.net/jeps/286

[source,java]
----
include::snippets/java10_var.jsh[]
----


Now it is possible to express things not possible before, use wisely:

[source,java]
----
var a = new Object() {

   void m() {

   }

};

a.m();

----

== Upgrade to Java9

=== JShell


=== Immutable collections

Gotcha: cannot use Set.of to filter aways duplicated.

[source,java]
----
jshell> Set.of(1,1).getClass()
|  java.lang.IllegalArgumentException thrown: duplicate element: 1
|        at ImmutableCollections$SetN.<init> (ImmutableCollections.java:463)
|        at Set.of (Set.java:521)
----

[AAA]
Immutability vs views: copyOf() is a new tool yielding an immutable copy of the datastracture. Collections.unmodificable* are just read-only wrappers around original data structure: if the original datastructure is mutable, you can still see changes in the wrapper.


=== Version

In legacy codebases it is possible to find some creative code around determining which java version
we are using:

[source,java]
----
String version = Runtime.class.getPackage().getImplementationVersion();
----

[source,java]
----
double version = Double.parseDouble(System.getProperty("java.specification.version"));
----

[source,java]
----
String[] javaVersionElements = System.getProperty("java.runtime.version").split("\\.|_|-b");
----


[source,java]
----
Runtime.Version version = Runtime.version();
----

[source,java]
----
include::snippets/java9_version.jsh[]
----


== Upgrade to Java8

=== java.io.UncheckedIOException

This is a little know class
