name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1.91.0
      with:
        ruby-version: 3.0
    - name: Check ruby
      run: ruby -v
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake
